function [] = showFlows(centers)

% plot the centers of the clustered trajectories
% cenetrs: a matrix generated by function clusterAllFlows

numCluster = size(centers,1);

colordim = floor(numCluster^(1/3));
cc = zeros((colordim+1)^3,3);
cc(:,1) = reshape(repmat(0:1/colordim:1,(colordim+1)^2,1),1,[]);
cc(:,2) = repmat(reshape(repmat(0:1/colordim:1,colordim+1,1),1,[]),1,colordim+1);
cc(:,3) = repmat(0:1/colordim:1,1,(colordim+1)^2);

% show the centers of flows one by one
figure;
for k = 1:numCluster
    gscatter(0,0,'r');
    hold on;
    for j = 1:size(centers,2)/2
        if j == 1
            p1 = [0,centers(k,2*j-1)];
            p2 = [0,centers(k,2*j)];
            h = plot(p1,p2);
            set(h,'color',cc(k,:));
        else
            p1(1) = p1(2);
            p2(1) = p2(2);
            p1(2) = p1(1)+centers(k,2*(j-1));
            p2(2) = p2(1)+centers(k,2*j);
            h = plot(p1,p2);
            set(h,'color',cc(k,:));
        end
        xlim([min(centers(k,1:2:end)) max(centers(k,1:2:end))]);
        ylim([min(centers(k,2:2:end)) max(centers(k,2:2:end))]);
        pause(0.1);
    end
    hold off;
    pause(0.1);
end 


end