function [angles,weights,indx] = getFlowAngle(trackVelBatch)

% calculate the angle of velocity vectors
% Input: 
%     trackVelBatch: defined in funciton extractTrackBatch
%     hydraParam: generated by function estimateHydraParam
% Output:
%     flowAngle: a cell array of the same dimension with trackVelBatch.
%         Each element contains the calculated angles for each time points
%         in rows, and each row represents one tracked cell within the
%         given time window.
%     flowWeight: a cell array that contains the corresponding weight
%         information of flowBatch. Weight is calculated by the length of
%         the velocity vector.


dimsBatch = size(trackVelBatch);
angles = [];
weights = [];
indx = [];

for i = 1:dimsBatch(1)
    for j = 1:dimsBatch(2)
        %if i==1&&j==1
        %    i;
        %end
        tmpmat = trackVelBatch{i,j};
        if ~isempty(tmpmat)
            dimmat = size(tmpmat);
            indx(end+1:end+dimmat(1),1) = i;
            indx(end-dimmat(1)+1:end,2) = j;
            % get flow angles and flow weights
            tmpangles = zeros(dimmat(1),dimmat(2)/2);
            tmpweights = zeros(dimmat(1),dimmat(2)/2);
            for k = 1:dimmat(1)
                tmpflow = reshape(tmpmat(k,:),[2,dimmat(2)/2]);
                tmpweights(k,:) = sqrt(sum(tmpflow.^2,1));
                tmpweights(k,:) = tmpweights(k,:)./sum(tmpweights(k,:));
                tmpangles(k,:) = atan(tmpflow(2,:)./tmpflow(1,:));
            end
            
            angles(end+1:end+dimmat(1),:) = tmpangles;
            weights(end+1:end+dimmat(1),:) = tmpweights;
          
        end
    end
end



end